/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    introSidebar: [
        // {
        //     type: 'category',
        //     collapsible: false,
        //     label: 'Intro',
        //     items: [{ type: 'autogenerated', dirName: 'intro' }],
        // },
        { type: 'autogenerated', dirName: 'intro' },
    ],

    coreSidebar: [
        // {
        //     type: 'category',
        //     collapsible: false,
        //     label: 'General',
        //     items: ['core/general'],
        // },
        // {
        //     type: 'category',
        //     collapsible: false,
        //     label: 'Core',
        //     items: [
        //         {
        //             type: 'category',
        //             label: 'Mathematics',
        //             items: [
        //                 {
        //                     type: 'autogenerated',
        //                     dirName: 'core/math',
        //                 },
        //             ],
        //         },
        //         {
        //             type: 'category',
        //             label: 'Programming',
        //             items: [
        //                 {
        //                     type: 'autogenerated',
        //                     dirName: 'core/programming',
        //                 },
        //             ],
        //         },
        //         {
        //             type: 'category',
        //             label: 'Object-Oriented',
        //             items: [
        //                 {
        //                     type: 'autogenerated',
        //                     dirName: 'core/object-oriented',
        //                 },
        //             ],
        //         },
        //         {
        //             type: 'category',
        //             label: 'Data Structures and Algorithms',
        //             collapsible: true,
        //             items: [
        //                 {
        //                     type: 'autogenerated',
        //                     dirName: 'core/datastructures-and-algorithms',
        //                 },
        //             ],
        //         },
        //         {
        //             type: 'category',
        //             label: 'Design Patterns',
        //             items: [
        //                 {
        //                     type: 'autogenerated',
        //                     dirName: 'core/design-patterns',
        //                 },
        //             ],
        //         },
        //         {
        //             type: 'category',
        //             label: 'Databases',
        //             items: [
        //                 {
        //                     type: 'autogenerated',
        //                     dirName: 'core/databases',
        //                 },
        //             ],
        //         },
        //         {
        //             type: 'category',
        //             label: 'Operating Systems',
        //             items: [
        //                 {
        //                     type: 'autogenerated',
        //                     dirName: 'core/operating-systems',
        //                 },
        //             ],
        //         },
        //         {
        //             type: 'category',
        //             label: 'Networks',
        //             items: [
        //                 {
        //                     type: 'autogenerated',
        //                     dirName: 'core/networks',
        //                 },
        //             ],
        //         },
        //     ],
        // },
        { type: 'autogenerated', dirName: 'core' },
    ],

    subfieldsSidebar: [{ type: 'autogenerated', dirName: 'subfields' }],

    resourcesAndGuidesSidebar: [
        // {
        //     type: 'category',
        //     collapsible: false,
        //     label: 'Resources',
        //     items: [{ type: 'autogenerated', dirName: 'resources' }],
        // },
        { type: 'autogenerated', dirName: 'resources' },
    ],

    // But you can create a sidebar manually
    /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
