/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure

    communityGeneralSidebar: [{ type: 'autogenerated', dirName: 'community/general' }],

    // communityRolesOnboardingSidebar: [
    //     { type: 'autogenerated', dirName: 'community/roles-onboarding' },
    // ],

    communityServicesOnboardingSidebar: [
        { type: 'autogenerated', dirName: 'community/services-onboarding' },
    ],

    // communityChannelsCategoriesOnboardingSidebar: [
    //     { type: 'autogenerated', dirName: 'community/channels-categories-onboarding' },
    // ],

    //--------------------------------------------------------------------------------

    resourcesCoursesSidebar: [{ type: 'autogenerated', dirName: 'resources/courses' }],

    resourcesCoreSidebar: [{ type: 'autogenerated', dirName: 'resources/core' }],

    resourcesSubfieldsSidebar: [{ type: 'autogenerated', dirName: 'resources/subfields' }],

    //--------------------------------------------------------------------------------

    otherResourcesSidebar: [{ type: 'autogenerated', dirName: 'other/resources' }],

    // resourcessSidebar: [
    //     // {
    //     //     type: 'category',
    //     //     collapsible: false,
    //     //     label: 'Intro',
    //     //     items: [{ type: 'autogenerated', dirName: 'intro' }],
    //     // },
    //     { type: 'autogenerated', dirName: 'resourcess' },
    // ],

    // resourcesAndGuidesSidebar: [
    //     // {
    //     //     type: 'category',
    //     //     collapsible: false,
    //     //     label: 'Resources',
    //     //     items: [{ type: 'autogenerated', dirName: 'resources' }],
    //     // },
    //     { type: 'autogenerated', dirName: 'resources' },
    // ],
};

module.exports = sidebars;
